### ISSUE TITLE
El mensaje "No entiendo ese verbo" ha sido cambiado

### ISSUE THREAD

**Issue by rubereaglenest** [sarganar/I7-Spanish#18]
En español tenemos esto:

>fnwlifnwleifn Makke
No entendí esa frase.

Pero el original inglés es así:

>ekokeofke
That's not a verb I recognize.

Esto es importante para que los jugadores entiendan dónde está el problema. Que sepan que el verbo que están usando no se usa en la aventura. Lo otro es demasiado ambiguo.

Sé que hay gente que no está de acuerdo con que el parser indique dónde está el error, pero ante la duda debemos ser fieles a Inform.

**Comment by rubereaglenest** [comment]
Es posible que no haya sido cambiado. Es posible que sea un error de infsp al asignar esos mensajes de error. Por este motivo:

  parser error internal rule response (A) is "No entendí esa frase.".
    parser error internal rule response (N) is "No conozco ese verbo.".

O sea que el mensaje correcto está ahí, pero no es aplica correctamente.

**Comment by sarganar** [comment]
Esto está funcionando correctamente en la r10.1. 🤷‍♂️
