### ISSUE TITLE
Usar "del" dentro de un Understand hace que no se procese

### ISSUE THREAD

**Issue by rubereaglenest** [sarganar/I7-Spanish#24]
Un caso raro raro

A libro is here. The description is "Es un ensayo sobre evangelios escrito por el padre Giovanni Lanfranco." The printed name is "Hijo del Hombre". Understand "hijo del hombre" as the libro.

>Examinar Hijo del hombre
No funciona.

Pero en cambio si definimos el Understand como "hijo de hombre" Sí funciona, e incluso usando del en el prompt:

>Examinar hijo del hombre
Es un ensayo sobre evangelios escrito por el padre Giovanni Lanfranco.

Raro eh?. Probablemente deba ser una incompatibilidad por los trucos para que de y del sean sinónimos o lo que sea. El problema es que el truco es fácil de olvidar y puede causar quebraderos de cabeza. Lo ideal es que dentro del Understand se pudiese pone "del" sin problemas.

**Comment by sarganar** [comment]
El parser spanish trasforma el input (del jugador) `del` a `de`, por lo que si usas el token 'del' en tu Understand lo haces inaccesible.

Por eso te funciona cuando pones 'Understand como "hijo de hombre"' y no te funciona cuando usas  Understand "hijo del hombre". 

Esto deberia documentarse como advertencia.
