### ISSUE TITLE
Problemas en ubuntu 16.04 64 bits al compilar con la extension

### ISSUE THREAD

**Issue by ByFernanz** [sarganar/I7-Spanish#25]
Hice varias pruebas, primero con la última release, tambièn probè clonando el repositorio, y también probé con una versión más antigua que me recomendó Johan. Con todas obtuve el mismo error de compilación que habla sobre la extensiòn de Sebastian que tiene un problema con los generos. Si quito "(in spanish)" entonces compila bien, pero sin el soporte en español.

**Comment by ByFernanz** [comment]
la forma de referir la extension en español "(in spanish)" por alguna razón no funciona en mi distribución de linux. Pero si hago el include de esta forma:

Include Spanish Language by Sebastian Arg.

Si que me reconoce el español.  Ahí sí que me funciona bien.

**Comment by sarganar** [comment]
Apliqué la solucion propuesta [en el foro ingles](https://intfiction.org/t/problem-with-italian-language-on-inform7-6m62-and-ubuntu/11706/4?u=sarganar), y aparentemente la cosa se solucionó.
