### ISSUE TITLE
El mensaje por sistema para dar cambia el género del personaje al del objeto

### ISSUE THREAD

**Issue by bert1978bc** [sarganar/I7-Spanish#28]
Cuando das un objeto a un personaje el mensaje por defecto cuando lo rechaza es "no parece interesado/a", pero cuando le das un objeto femenino a un personaje masculino el mensaje que aparece es "X no parece interesada".
Lo he solucionado cambiado la respuesta así: The block giving rule response (A) is "No muestra interés."
No sé si también podría funcionar lo siguiente: The block giving rule response (A) is "[The second noun] no muestra interés."

**Comment by sarganar** [comment]
Gracias por detectarlo. Creo que ahi está corregido. La actualizacion está subida al master branch.

**Comment by bert1978bc** [comment]
Mil gracias a ti. La extensión es una maravilla.
