### ISSUE TITLE
Pruebas de r10.1

### ISSUE THREAD

**Issue by brtl-fhc** [sarganar/I7-Spanish#29]
Hola @sarganar,

muchas gracias por tu trabajo con la nueva versión de I7SP. He probado a compilar varios proyectos con ella, y sólo me ha funcionado Estado Profundo, mi último juego (el código aún no está publicado pero tengo pensado hacerlo, te lo puedo hacer llegar.

La versión que he generado es ejecutable y se puede terminar. He visto pequeños problemas de capitalización (ver ejemplos abajo) y de algunos verbos sólo funcionan las formas en imperativo. También he echado en falta algún sinónimo (por ejemplo con los dispositivos: en España es habitual "encender" como sinónimo de "conectar").

Ejemplos:

>abrir maleta
No conozco ese verbo.
 
>abre maleta
Abres La maleta, descubriendo Las piezas de fusil.

...

>encender ordenador
No conozco ese verbo.
 
>conectar ordenador
Enciendes El ordenador.

...

>salir
No conozco ese verbo.
 
>sal
(abriendo primero La puerta de salida al pasillo)
Sales corriendo al pasillo y te diriges a las escaleras. Bajas hasta la plaza y, aprovechando el caos, te fundes con la multitud.
 
...

> Sobre La encimera ves El libro y La vela.
(solía poner "Sobre la encimera ves un libro y una vela.").

Gracias de nuevo por tu gran labor!

**Comment by sarganar** [comment]
Okis, gracias por informarlo.

**Comment by sarganar** [comment]
Cómo estas? necesitaria un favorcicto: ¿podrias pegar aqui el codigo minimo para reproducir la salida 2, 4 y 7?

**Comment by jramirez-cl** [comment]
Hola, lo probaré pero tardaré unos días, tengo instalado el entorno en mi ordenador personal.

**Comment by brtl-fhc** [comment]
Hola, ahora mismo no puedo probar, pero era este código fuente:

[story.ni.txt](https://github.com/sarganar/I7-Spanish/files/11846137/story.ni.txt)

Gracias por tu gran trabajo!

**Comment by sarganar** [comment]
He corrido algunos test en tu codigo. Veo que cuando creas un objeto, como el ordenador dices:

```
El ordenador is a device.
```

Realmente debes decir:

```
The ordenador is a device.
```
 Porque de lo contrario I7 te toma "El ordenador" como el nombre del device que estás creando, y lo utiliza así en los parrafos que genera automáticamente.

**Comment by sarganar** [comment]
Así mismo,  en caso de objetos femeninos como la maleta, puedes hacer:
```
A maleta (f) is in la Habitación 10023.
```

De esa forma le dices a I7 que es un objeto femenino, y entonces responderá correctamente en comandos como:

```
>x maleta
Una maleta industrial reforzada. Está cerrada.

>abrela
Abres la maleta, descubriendo Las piezas de fusil.

Desde el exterior entra el sonido atronador de los aplausos. Empieza el acto de fin de campaña del Partido del Futuro.

>coge
¿Qué quieres coger?

>maleta
Cogida.

>i
 Llevas:
  una maleta (abierta)
    Las instrucciones
    Las piezas de fusil
  Los guantes (que llevas puesto)

>
```
