### ISSUE TITLE
Eliminar rutinas verbo irreglar

### ISSUE THREAD

**Issue by sarganar** [sarganar/I7-Spanish#6]
¿Con el nuevo I7; ya no harían falta los objetos VerboIrregular?

**Comment by rubereaglenest** [comment]
¿Por qué? ¿Cuál es la alternativa?

Es que he estado buscando una manera de definir nuevos verbos irregulares y al final he tenido que copiarme de infsp:

Include (-
VerboIrregular "ungir" with imperativo 'unge';
-)

Si hay una alternativa mejor me gustaría saberla.

**Comment by sarganar** [comment]
En la nueva release de infsp7 al fin la clase VerboIrregular se reemplaza por una Tabla de Verbos Irregulares.
